### ISSUE TITLE
'cli_wallet`-locking on wrong request from command line

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/golos#498]
**Steps to reproduce**
Run multiple `cli_wallet` in parallel:
```bash
#> for i in {0..1000}; do ./cli_wallet --server-rpc-endpoint="ws://127.0.0.1:8091" --command='get_account not-exists' &; done
```

**Actual result**
There are some `cIi_wallet`s that is in locking state:
```bash
#> ps axfwwu | grep cli_wallet | grep -v grep | wc -l
8
```

**Expected result**
There are no more `cli_wallet`
```bash
#> ps axfwwu | grep cli_wallet | grep -v grep | wc -l
0
```

**Comment by afalaleev** [comment]
This bug may be was fixed in #487, but it should be checked.

**Comment by zxcat** [comment]
This (or similar) bug is still there, getting it on local testnet node.
Additionally got some segfaults when checked this steps on remote mainnet node (maybe rate limit related).

**Comment by afalaleev** [comment]
May be a similar bug with publishing feeds via the shell-script from https://golos.io/ru--delegaty/@xtar/bash-skript-dlya-avtomaticheskoi-publikacii-fida
![default](https://user-images.githubusercontent.com/27198658/38975778-51609cb4-43d9-11e8-8175-83b1e96ef5ec.jpg)
